name: page_view_indicator
version: 2.0.3
description: Builds indication marks for PageView from any Widget and/or Animation.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/page_view_indicator

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
